# Generated by Django 3.0.5 on 2020-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='uuid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
