# Generated by Django 3.0.5 on 2020-05-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardauth', '0003_oauth2token_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('oauth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boardauth.OAuth2Token')),
            ],
        ),
    ]
