# Generated by Django 3.0.5 on 2020-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardauth', '0004_eurologin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurologin',
            name='cookie',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
